### ISSUE TITLE
Support app shortcuts for saved servers

### ISSUE THREAD

**Issue by capatina** [gujjwal00/avnc#127]
Hi there,

We need the ability to specify a connection that the app should attempt as soon as it is launched (setting up an android tablet as a controller for a machine).

are you able to add this in?

Thank you!

Sebastian

**Comment by gujjwal00** [comment]
Sorry, I am not going to add this. AVNC already supports `vnc://` URLs to directly launch a connection, and I don't think single tap on app startup is too difficult.

**Comment by capatina** [comment]
@gujjwal00 can you explain a bit how `vnc://` URLs works? Do we enter them in chrome and it will open avnc with the connection? How do we use them?

**Comment by gujjwal00** [comment]
A VNC URL is similar to HTTP URLs you see in browser address bar. But instead of a web server, it identifies a VNC server.
Example: `vnc://10.0.0.1:5901/?VncPassword=foobar` (it will connect to a VNC server at `10.0.0.1`, on port number `5901`, with password `foobar`)

You cannot directly type these in Chrome to launch AVNC, because Chrome expects a HTTP URL. But there are many different ways, depending on your need. If you want to simply create a shortcut to a particular connection, you can use [Shortcut Manager](https://play.google.com/store/apps/details?id=rk.android.app.shortcutmaker). If you want to launch it automatically, e.g. at Boot, you can use [Automate](https://play.google.com/store/apps/details?id=com.llamalab.automate). These apps can be a bit confusing at first, so let me know if you need any help.


On the other hand, I have been planning to implement shortcuts like these for a while now:
![image](https://user-images.githubusercontent.com/27951674/213754375-ac2c1255-6917-49e2-907b-77fba516e0ae.png)

This will remove the need to use any third-party apps to create shortcuts.

**Comment by capatina** [comment]
Very helpful thank you! Can you make an issue for the shortcuts functions that I can follow?

This way we'll know when it's done!

**Comment by gujjwal00** [comment]
I will simply reopen this with modified title.

**Comment by gujjwal00** [comment]
Implemented in https://github.com/gujjwal00/avnc/commit/7e2f91e3c4442d637c2dc581995f24e9833b4214
Test APK: https://github.com/gujjwal00/avnc/suites/11105929824/artifacts/565694880

Few notes:
- Only servers with non-empty names will be available in shortcuts
- Due to system limit, only first four servers will be available as shortcuts
