### ISSUE TITLE
Color problem

### ISSUE THREAD

**Issue by MungJI** [gujjwal00/avnc#150]
I connected the Windows server with avnc software, but the color was wrong, as shown in the picture below. But I used other Android vnc programs and it worked fine

![IMG_20230310_141734](https://user-images.githubusercontent.com/45352612/224241896-98650bc3-7c2e-4e49-b4d3-89de675bae6c.jpg)

**Comment by gujjwal00** [comment]
Please tell me 
1. Server name
2. Server version

Have you tried using the MultiVNC app?

**Comment by MungJI** [comment]
1、Windows Server 2012
   use http://en.wovnc.com/  as vnc server. 
   avnc version: 2.1.2

2、I just tried the MultiVNC app，Choose different color patterns
   24-bit color (4 bpp)： as avnc，color is wrong
   16-bit color (2 bpp)：color is right
![2](https://user-images.githubusercontent.com/45352612/224249556-49cd00ee-c987-43e0-838f-07f63909ce92.jpg)

**Comment by gujjwal00** [comment]
Thanks.
This may be similar to a bug I saw sometime ago. It happens because the server doesn't respect the pixel format sent by client. Thus the red & blue components are switched with each other.

You should try to contact the server developer once, see if they are willing to fix the issue. If they are not supportive, we can find a workaround for AVNC.
