### ISSUE TITLE
Allow Typing mode Keyboard

### ISSUE THREAD

**Issue by Sepero** [gujjwal00/avnc#187]
Normally I use a gesture type keyboard for everything. But the keyboard also has a "password entry" mode that disables gesture typing and forces tap-to-type. appears AVNC is stuck in this tap-to-type mode by default, without anyway to change it

My request is that AVNC allow the keyboard to default to gesture typing mode, and allow the user to switch to tap-to-type if the user desires

**Comment by gujjwal00** [comment]
Keyboard handling in AVNC is slightly different than what you normally expect from Android text views. Because VNC protocol works on individual keystrokes, we have to disable some features of Android input mechanism. Basically, AVNC pretends to be a dumb text view without support for caret, text selection, word replacement etc. This might be the reason why your keyboard is stuck in tap-to-type mode.

Can you please go to **Settings > Tools > Key test** in AVNC, and see if swipe typing is disabled there too?

**Comment by Sepero** [comment]
Yes, swiping is disabled in Key Test too

I also have RealVNC installed. RealVNC defaults to my normal swipe keyboard, and allows switching to tap-to-type for entering things like passwords

**Comment by gujjwal00** [comment]
https://github.com/gujjwal00/avnc/issues/117#issuecomment-2037693965 will add an edit box, which should allow you to use swipe keyboard.

**Comment by gujjwal00** [comment]
v2.5 is now available with this change.
