### ISSUE TITLE
.ssh/config

### ISSUE THREAD

**Issue by PowaBanga** [gujjwal00/avnc#190]
Hi everybody,
Is there a place somewhere where i can write a .ssh/config ?
So i can have more elaborated connection with tunnels.

**Comment by gujjwal00** [comment]
No, .ssh/config is not supported in AVNC. We don't use the normal `ssh` client to create SSH connection. Instead we use ConnectBot's SSH library for this task.

If you want more elaborate setup, you should launch `ssh` client from a terminal app and then provide address of the tunnel to AVNC (instead of the actual VNC server).
