### ISSUE TITLE
Option for low latency

### ISSUE THREAD

**Issue by allytiago** [gujjwal00/avnc#192]
The option would be to try to reduce as much as possible the latency that exists in the local vcs server and the AVNC app and try to make the experience much closer to what it would be like when using it on a normal desktop.  I believe that the latency would not be good in the case of using a VNC web server like AWS, but a localhost could have a much lower latency.

 Currently I notice a delay when I enter text or perform an action.

**Comment by gujjwal00** [comment]
Hi @allytiago, sorry for late response.

While some delay is inevitable due to the nature of VNC protocol, you can try couple of options to reduce it:
1. Disable image compression: Go to Advanced server options and enable **Raw** Image Quality. Image compression is not necessary in case of local server as you are not constrained by network bandwidth.
2. Disable encryption: You can disable encryption by setting **Security** to *None* or *VncAuth* in advanced server options.

AVNC already tries its best to reduce latency in all cases, so adding a separate option is not necessary.
