### ISSUE TITLE
1080高清視頻顯示garbage

### ISSUE THREAD

**Issue by TumaLiu** [gujjwal00/avnc#197]
server端播放1080高清視頻，AVNC畫面解析異常，顯示如圖所示的garbage
![Uploading garbage.png…]()

**Comment by TumaLiu** [comment]
![garbage](https://github.com/gujjwal00/avnc/assets/92851386/272a2e54-21cf-4752-ad63-0f2ca2ab172e)

**Comment by gujjwal00** [comment]
Hi @TumaLiu, please let me know your:
- VNC server
- Operating system

Also, please check if the following app also shows the same issue: https://github.com/bk138/multivnc

**Comment by TumaLiu** [comment]
Hi,
Thank you for your prompt reply!

- VNC server: x11VNC for Linux
- Operating system: AVNC running in Android Studio AVD
-  "https://github.com/bk138/multivnc" have the same issue.

What are some other possible reasons?Looking forward to your response~

**Comment by gujjwal00** [comment]
If MultiVNC is also affected, the issue is more likely to be present in LibVNCClient. There are a few things you can try to isolate the issue:
- Try using the 'Raw' encoding (enable *Raw* image quality in Advanced server options) in AVNC. In this mode raw pixel data is exchanged. It might be very slow for 1080p video, but if it removes the artifacts, then we know the issue is related to image encoding.  
- Try using another app like bVNC (or a different VNC server) to rule out any server side issue.

**Comment by TumaLiu** [comment]
Using the 'Raw' encoding, the garbage problem still persists,perhaps to a lesser extent.
I try another server-tightVNC,and the problem also exists.

Other suggestions??

**Comment by TumaLiu** [comment]
Sorry! correct it:
I try another server-tightVNC for Windows have not this garbage issue. 
The garbage issue happens on x11VNC for Linux server.

**Comment by gujjwal00** [comment]
So x11vnc can be the culprit. I suggest you switch to another VNC server if you can as x11vnc is currently unmaintained.
