### ISSUE TITLE
Clarification of zoom in/out numbers?

### ISSUE THREAD

**Issue by sudomain** [gujjwal00/avnc#42]
Hello,

I'm trying to grasp what the numbers repesent for the min/max zoom. Is it a percentage of the geometry of the vnc server? Setting both min and max zoom to 100% seems to disable zooming as expected, but it leaves about 50% (I'm eyeballing this) of my screen filled with unused black pixels.

As potential feature requests:
1. could both of the zoom settings be made to accept a wider range of numbers?
2. could there be a zoom setting for the default zoom when avnc connects to the server (of course it would have to be between the min/max settings)

I am using tigervnc server with an uncommon geometry of 720x1280, so maybe that's what's messing things up :)

**Comment by gujjwal00** [comment]
Yes, the numbers for min/max zoom represents percentage (maybe adding the `%` symbol would clarify it further). When you connect, you always start at 100% zoom, irrespective of the screen size (Android's or remote's).

Let me explain it a bit more. At 100% zoom, AVNC tries to achieve following goals:
- Remote display is *completely* visible
- Aspect ratio of remote display is maintained
- Maximum screen space is utilized in landscape mode<sup>*</sup>, while maintaining previous two constraints.

\* In reality, we look at the longer side of the activity window, but this difference is only visible in multi-window mode.

So, for example, if you have an Android device of size 100x50:
-  Remote display of 100x50 will fit completely
-  Remote display of 100x30 will be centered vertically & completely filled horizontally
-  Remote display of 50x25 will also fit completely, due to same aspect ratio 
-  Remote display of 50x100 will be centered horizontally & completely filled vertically

> 1. could both of the zoom settings be made to accept a wider range of numbers?

We can make it however wide we want. In code, its just a number: 1 is 100%, 1.5 is 150%, 2.1 is 210% etc. I originally limited it to 500%, because with larger numbers, the seekbar user for zoom preference was harder to operate. But I think if we increase the step-size form 1 to, say 5, we should be good.

> I am using tigervnc server with an uncommon geometry of 720x1280, so maybe that's what's messing things up :)

Yes that definitely is the issue here, as we are not optimizing for remote display's orientation right now. But I think that can be fixed.

Let's say you local screen is also 720x1280 (or something else with this aspect ratio), and AVNC completely fills the screen in portrait mode at 100% zoom, would that remove the need for your second feature request?

**Comment by sudomain** [comment]
Sorry for my weird config/edge case lol. Thank you for the detailed response.

> Let's say you local screen is also 720x1280 (or something else with this aspect ratio), and AVNC completely fills the screen in portrait mode at 100% zoom, would that remove the need for your second feature request?

Yes please!

On a related note to screen geometry, I also noticed that avnc's full screen setting only hides the notification tray but not the navigation bar (Back, Home, Recent buttons) which in turn would lower my useable vertical area at 100% zoom. Could full screen be made to hide the nav bar also please? If not, I could try to account for the height of the Android nav bar in vnc server config.


P.s. I'm aware of your work on both this and MultiVNC and wish to extend my sincere thanks!

**Comment by gujjwal00** [comment]
> Could full screen be made to hide the nav bar also please?

Please turn on `Settings => Experimental => Full immersive mode`. This is marked as experimental, because it interferes with toolbar/sidebar drawer when both of them are on same edge, and I don't have a clean solution to this interference yet.

> P.s. I'm aware of your work on both this and MultiVNC and wish to extend my sincere thanks!

Appreciate it very much.

Will try to solve the zooming issue tomorrow.

**Comment by gujjwal00** [comment]
@sudomain Can you please try this APK: [app-debug.zip](https://github.com/gujjwal00/avnc/files/7819727/app-debug.zip)

**Comment by sudomain** [comment]
Hey is the code in that apk going into the Fdroid build or was this one those `generously build a niche apk for a niche usecase` situations? Thanks either way

**Comment by gujjwal00** [comment]
Yeah, it was a quick fix. Here is the patch, if you want to try it yourself:
```diff
From 4ea582f58a03781683ccc4053ac3b0e259cc9281 Mon Sep 17 00:00:00 2001
From: Gaurav Ujjwal <******@gmail.com>
Date: Thu, 6 Jan 2022 15:20:06 +0530
Subject: tmp


diff --git a/app/src/main/java/com/gaurav/avnc/ui/vnc/FrameState.kt b/app/src/main/java/com/gaurav/avnc/ui/vnc/FrameState.kt
index 4d3a7a3..a26d2cc 100644
--- a/app/src/main/java/com/gaurav/avnc/ui/vnc/FrameState.kt
+++ b/app/src/main/java/com/gaurav/avnc/ui/vnc/FrameState.kt
@@ -193,8 +193,8 @@ class FrameState(private val minZoomScale: Float = 0.5F, private val maxZoomScal
 
         //Base scale is calculated as-if we are in 'Landscape' mode.
         //So larger window side is treated as width and smaller as height
-        val wRatio = max(windowWidth, windowHeight) / fbWidth
-        val hRatio = min(windowWidth, windowHeight) / fbHeight
+        val wRatio = max(windowWidth, windowHeight) / max(fbWidth, fbHeight)
+        val hRatio = min(windowWidth, windowHeight) / min(fbWidth, fbHeight)
 
         baseScale = min(wRatio, hRatio)
     }
```
It literally has the commit message `tmp` 😄. 

Although the fix is simple, I just want to add some [tests](https://github.com/gujjwal00/avnc/blob/master/app/src/test/java/com/gaurav/avnc/ui/FrameStateTest.kt), but I was busy with some string cleanup work. It will definitely be included in the next release.

**Comment by gujjwal00** [comment]
And BTW, the APK I posted was a debug build, so it will slower compared to a release build.
