### ISSUE TITLE
Request: differentiate/increase tolerance between "Long Press" and "Drag (Long Press then Swipe)"

### ISSUE THREAD

**Issue by sudomain** [gujjwal00/avnc#43]
Hello again,

Under the input settings, I'm trying to use:
1. "Long Press" to right click and
2. "Drag (Long Press then Swipe)" to drag remote content.

Unfortunately, changing the Drag setting causes
me to be unable to perform a long press. I'm guessing that when I attempt a long press, my fingers can't stay still long enough so Drag gets triggered instead of just Long Press.

Can there please be an increased tolerance (whether a setting or just baked into the app) to allow both long press and drag to be used? For example, maybe if X and Y of the cursor hasn't changed by more than ~5 pixels in 500 ms then Long Press, Drag if otherwise?

**Comment by gujjwal00** [comment]
Please see #6 . (precisely https://github.com/gujjwal00/avnc/issues/6#issuecomment-938681390).
Improving this experience is on my todo list, but for now I want to finish #5 before doing anything else touch related.

**Comment by sudomain** [comment]
Per your comment in #6, I'm unable to get a regular long press to trigger no matter how still I try to keep my finger (if drag is enabled). I even tried with a stylus. To the best of my knowledge, I don't have particularly shaky hands lol.

I can get by with using a double tap for right click. Thanks again for the app.

**Comment by gujjwal00** [comment]
@sudomain please test this APK:  [app-debug.zip](https://github.com/gujjwal00/avnc/files/7834706/app-debug.zip)

It should reliably differentiate between long press (touch-hold-release), and drag (touch-hold-swipe).

**Comment by sudomain** [comment]
Thank you! It works great and I can do both gestures now. Is the "touch slope" something that the user could configure? With this apk I notice a slight XY inaccuracy between where I'm trying to start a drag and where AVNC actually starts a drag action. I think it's somewhere in the neighborhood of 10-20 pixels based on my desktop icon setting of 48x48px. If it's not possible, I can live with "leading" my drag actions.

**Comment by gujjwal00** [comment]
Touch slope is automatically determined by Android, based on things like screen density and device configuration.

I think the issue is that drag was started from the point where swipe was first detected, and not from the point where finger initially went down. But by that point, finger had already moved more than touch slop, so that small distance was effectively lost.

I am attaching a new APK: https://github.com/gujjwal00/avnc/suites/4876806747/artifacts/139390680
Commit: https://github.com/gujjwal00/avnc/commit/823a633edcf232fec7cdb282a014077adf654c62
This should fix the issue. You will have to uninstall the previous one.
> I'm not the best at phrasing things and I hope this didn't come off as unnecessarily nitpicky or ungrateful.

No, you are absolutely fine :+1: , and thank you for reporting this issue. I probably would not have encountered it myself.

**Comment by sudomain** [comment]
Everything is perfect now. Thank you for your responsiveness and all your work!
