### ISSUE TITLE
Having trouble exporting server list...

### ISSUE THREAD

**Issue by JacobArcos** [gujjwal00/avnc#82]
**Description**

Can you change the type of authentication or make it optional in the file:
`app/src/main/java/com/gaurav/avnc/ui/prefs/ImportExportFragment.kt`

Beacuse my device doesn't have biometric hardware and that makes impossible exporting my server list.

look the video [here](https://user-images.githubusercontent.com/75540925/170310917-fb9e2371-916a-4016-9e8e-4734f1511148.mp4)

**Additional Info**
- App Version: 1.8.1 (11)
- Android Version: 10 (29)
- Device Model: Lenovo TB-X606F

**Comment by gujjwal00** [comment]
Hi @JacobArcos , Before requiring authentication,  AVNC checks whether any authentication method (biometric/password/pattern etc) is actually enabled on the device. If there is no authentication, AVNC will not ask for it.  So it's possible that this is a bug in AndroidX Biometric library used by AVNC (or AVNC itself) where authentication method is incorrectly detected.

Can you please try setting a screen lock with password/pattern in Android Settings?

Adding an option for this behavior is slightly tricky because then that option will have to be protected by authentication. Otherwise anyone can turn off that option.

**Comment by JacobArcos** [comment]
Hello @gujjwal00, In my Lenovo TB-X606F I have a pattern for the screen lock, you should see [this video](https://user-images.githubusercontent.com/75540925/170310917-fb9e2371-916a-4016-9e8e-4734f1511148.mp4) if you haven't seen it beacuse it doesn't even ask for password, pattern, or anything... it just returns the error "Biometric hardware unavailable."

What should I do?
Does this require the latest version of Google Services Framework?
beacuse my GSF software is outdated.

**Comment by JacobArcos** [comment]
[Here is other video without drawings](https://user-images.githubusercontent.com/75540925/170382361-f281e848-8119-485c-bcd4-3d54f14ccfc3.mp4)

**Comment by JacobArcos** [comment]
[here](https://user-images.githubusercontent.com/75540925/170382542-6085ae85-5a3d-4266-ab6d-04ad55773590.mp4) is another video, but without drawings

**Comment by gujjwal00** [comment]
Thanks for the videos, they are really helpful and did watch the first video you linked.

I have updated the Biometric library to [latest version](https://developer.android.com/jetpack/androidx/releases/biometric#1.2.0-alpha04). It includes couple of fixes related to some Android 10 devices.
Can you please try the following APK: [app-debug.zip](https://github.com/gujjwal00/avnc/files/8775510/app-debug.zip).
See if this debug APK correctly asks for you pattern.

AVNC does not use GSF at all, so it should not be a factor here.

**Comment by JacobArcos** [comment]
And now the problem has been solved!

Thanks 😀.
