### ISSUE TITLE
Feature request: enable direct touch mode or "pointer" mode on a per-host basis

### ISSUE THREAD

**Issue by sudomain** [gujjwal00/avnc#86]
I like both direct touch mode and its alternative ("pointer mode"? I'm not sure of the name), but frequently find myself going into the settings to switch between the two depending on the host I'm connecting to. Direct touch mode works well for my Android hosts (using droidVNC-ng) and pointer mode works well for my *nix hosts running a variety of window managers that aren't optimized for touch. Would it be possible to configure the desired mode on a per-host basis I.e. on the screen with the "Edit server" title?

**Comment by gujjwal00** [comment]
So I have been thinking about this, and per-host gesture mode seems a better choice to me too.
- As you said, different modes may be more suitable for different hosts. Original idea was that it is a *per-user* preference.
- Since releasing this feature, I have seen users getting confused about the terminology around 'Direct touch'. This terminology spilled over from code, where these modes are called [`DirectMode`](https://github.com/gujjwal00/avnc/blob/b3bd9399f0e264456c36e3d7a03765aa00a815ca/app/src/main/java/com/gaurav/avnc/ui/vnc/Dispatcher.kt#L235) & [`RelativeMode`](https://github.com/gujjwal00/avnc/blob/b3bd9399f0e264456c36e3d7a03765aa00a815ca/app/src/main/java/com/gaurav/avnc/ui/vnc/Dispatcher.kt#L246). So we can take this opportunity to reduce this confusion.

##
Here is a quick prototype of 'Gestures' in advanced server options:


<img src="https://user-images.githubusercontent.com/27951674/178135404-ce5ea52d-06ac-456d-ba10-bd0fc39f5cc9.png" width="300"/> <img width="50"/> <img src="https://user-images.githubusercontent.com/27951674/178135396-91d71621-8df4-46d2-b346-d7b227051eff.png" width="300"/>

##
- Behavior of the two modes should be more clear now.
- About the **Direct touch** preference: I think it will be redundant after adding per-host **Gestures** option, so it should be removed. However, I am open to suggestions. 
- Any feedback about the wording/UI of new per-host option is welcome.

**Comment by sudomain** [comment]
IMO it looks great and the new wording is much clearer. I noticed the `One-finger swipe` gesture gets disabled when direct touch is disabled. If the preference is removed, then should `One-finger swipe` have a note added to make it clear it only applies to relative mode?

**Comment by gujjwal00** [comment]
After further investigation, I don't think we can remove 'Direct touch' preference without reducing functionality. Per-host option will not work for the connection started via following methods:
- From top Urlbar
- Tapping on discovered servers
- `vnc://` URIs (via Android Intents)

So instead of removing, it has to be re-worded to match new terminology. And now per-host option has to provide another 'Automatic' choice, which falls back to global Setting. New Prototype:

<img src="https://user-images.githubusercontent.com/27951674/178320159-c04602ac-7c9b-4f2c-9258-704bfda59117.png" width="300"/>

I also removed 'Like' from choices and changed 'Gestures' to 'Gesture style'. It seemed slightly cleaner this way.

**Comment by gujjwal00** [comment]
Final implementation: https://github.com/gujjwal00/avnc/commit/4dbfaf4a71eb7a6ac37f458e70d1f7117077cd3b
Test APK: https://github.com/gujjwal00/avnc/suites/8969083439/artifacts/412379656

It will be available in next release.

**Comment by gujjwal00** [comment]
[v2.0.0](https://github.com/gujjwal00/avnc/releases/tag/v2.0.0) is now available.

**Comment by sudomain** [comment]
Thank you!
